---

- name: Pull for PI
  hosts: localhost
  user: root
  connection: local 

- name: "redis is installed"
  apt:
    name: redis-server

- service:
    name: redis-server
    state: started
    enabled: true
