---

- name: "redis is installed"
  apt:
    name: redis-server  
  
- service:
    name: redis-server 
    state: started
    enabled: true

- name: "python3 is installed"
  apt:
    name: python3
- name: "virtualenv is installed"
  apt:
    name: python-virtualenv
- name: "pip is installed"
  apt:
    name: python3-pip

- pip:
    name: PyBarCodeScan 
    virtualenv: /venv
    state: latest
      
- service:
    name: barcodescanner_server
    state: started
    enabled: true
- service:
    name: barcodescanner_reader 
    state: started
    enabled: true
